# Generated by Django 5.2 on 2025-05-07 08:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_department_userprofile_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
