# Generated by Django 5.2 on 2025-05-07 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_survey_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='teacher_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teachersubject'),
        ),
    ]
