# Generated by Django 5.2 on 2025-05-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_survey_teacher_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='characteristic',
            field=models.CharField(choices=[('Общее впечатление', 'Общее впечатление'), ('Содержание курса', 'Содержание курса'), ('Преподавание', 'Преподавание'), ('Организация и предмет', 'Организация и предмет')], max_length=100),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='type',
            field=models.CharField(choices=[('text', 'Открытый'), ('choice', 'Выбор одного варианта'), ('multi', 'Выбор нескольких вариантов')], default='choice', max_length=20),
        ),
    ]
