# Generated by Django 5.2 on 2025-05-08 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_questionbank_characteristic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_score', models.FloatField(default=4.0, verbose_name='Средний балл')),
                ('attendance_ratio', models.FloatField(default=0.9, verbose_name='Посещаемость (0-1)')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='core.student')),
            ],
        ),
    ]
