# Generated by Django 5.2.1 on 2025-05-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_studentdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='number',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
